### ISSUE TITLE
Variables can't exceed 99.99

### ISSUE THREAD

**Issue by evaneaston** [Zolko-123/FreeCAD_Examples#1]
I started tutorial 2 and found I could type in 100.00 for R_disk .  The max that the spinner/text field will let me enter is 99.99.  I'm running FreeCAD 0.19-19510 and Assembly 4 0.7.12, 2020-01-25.

![Assembly4Tutorial2Issue](https://user-images.githubusercontent.com/5614092/74535085-b7c2aa00-4efa-11ea-8d97-dfb81aa49481.gif)

**Comment by evaneaston** [comment]
I'm closing and moving this over to the correct project.

**Comment by Zolko-123** [comment]
On 14 February 2020 14:22:20 Evan Easton <notifications@github.com> wrote:
> I started tutorial 2 and found I could type in 100.00 for R_disk . The max 
> that the spinner/text field will let me enter is 99.99. I'm running FreeCAD 
> 0.19-19510 and Assembly 4 0.7.12, 2020-01-25.

Did you try with the latest 0.8.0 ?

Z.

**Comment by evaneaston** [comment]
Yes.  I noticed the latest build right after reporting the issue, updated and got past the issue.  Thanks.
