### ISSUE TITLE
Tutorial1 has invalid link to bearing step file

### ISSUE THREAD

**Issue by bukshanekom** [Zolko-123/FreeCAD_Examples#13]

**Comment by xiaomingneo** [comment]
Invalid link:
[bearing_20x37x9.stp](https://github.com/Zolko-123/FreeCAD_Examples/blob/master/Asm4_Tutorial1/bearing_20x37x9.stp)

Valid link:
[bearing_20x37x9.stp](https://github.com/Zolko-123/FreeCAD_Examples/raw/master/Asm4_Tutorial1/bearing_20x37x9.stp)
