### ISSUE TITLE
Asm4_Tutorial2 - README.md file: Sketch_master 

### ISSUE THREAD

**Issue by mantielero** [Zolko-123/FreeCAD_Examples#15]
I am not sure if this is an error or that I am not following well the tutorial. 

The tutorial says:
- Call it Sketch_master
  - **This will launch the attachment dialog of the sketch**

I don't have that behaviour. The Attachment appears with **Map Mode: Deactivated**. I need to click there in order to select a reference.

Also, I think is missing the creation of the LCS for each part:
- **As first reference, select the LCS_0 in the model tree (or type LCS_0 by hand into the field)**

**Comment by Zolko-123** [comment]
That's the attachment editor, and it indeed starts with a deactivated attachment, which is natural
