### ISSUE TITLE
Tutorial 2 LCS_pivot can't be made as described

### ISSUE THREAD

**Issue by hlovatt** [Zolko-123/FreeCAD_Examples#19]
The instructions for LCS_pivot says "Attach LCS_pivot to the original LCS of the part arm (called LCS_1002 in our design, this might be different for your model) with the Object's X Y Z mode". Unfortunately this isn't possible, you can't select "Object's X Y Z mode", it is permanently set to "XY on plane". The problem with this is that the animation fails.

Instead you need to select the edge of the hole and set to concentric.

Note link given to working model select the chamfer and sets mode to concentric.

**Comment by jkadofo** [comment]
Original instructions have worked fine in my case.
