### ISSUE TITLE
Assembly 4 Tutorial 2 naming inconsistencies.

### ISSUE THREAD

**Issue by crashkopf** [Zolko-123/FreeCAD_Examples#20]
I was working through the AWS tutorials and was confused by some instructions.  

- The "New Model" command nomenclature has been changed.  It is now "New Assembly".
- The instructions say to attach the master sketch to "LCS_0", but I got "links go out of scope" warnings.  The tutorial file was consistent with the instructions, but starting with a new file the correct name is "LCS_Origin".

**Comment by Zolko-123** [comment]
yes, well, sorry. You're welcome to propose corrections
