### ISSUE TITLE
Cannot Add LCS to Externally Linked Parts

### ISSUE THREAD

**Issue by d-v-t** [Zolko-123/FreeCAD_Examples#21]
I created a new assembly with some references for bodies from other files. All was going well until I attempted to place LCSes on these bodies: I got the message Error: No object named _Feature name_.

To test my hypothesis that it was related to referencing bodies, I created a body directly in the assembly (no reference) and attached an LCS without any problems.

I attached my files for this assembly. Hopefully they demonstrate my issues.

[cnc v3.zip](https://github.com/Zolko-123/FreeCAD_Examples/files/8691327/cnc.v3.zip)
.

**Comment by Zolko-123** [comment]
you cannot place LCSs on linked objects. You must place them directly into the Part/Body. If you need to have the LCS in the assembly (to place the assembly for example) then you need to import the LCS into the assembly with the dedicated function "Import Datum"
