### ISSUE TITLE
Slow animation

### ISSUE THREAD

**Issue by leoheck** [Zolko-123/FreeCAD_Examples#3]
Hi, I am experimenting with your plugin and examples. 
I am following the `Animate master sketch` from this readme, it looks nice but I have a question. The animation looks slow, it is not fluid as I expect. So, Is this an issue from my side (computer/tool_version) or it is something expected?

**Comment by leoheck** [comment]
By the way...

OS: Ubuntu 20.04 LTS (ubuntu:GNOME/ubuntu)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.21125 (Git) AppImage
Build type: Release
Branch: master
Hash: 40600a55c2fe71ff589be677f6e427ccc937d003
Python version: 3.8.2
Qt version: 5.12.5
Coin version: 4.0.0
OCC version: 7.4.0
Locale: English/United States (en_US)

![image](https://user-images.githubusercontent.com/1277920/82738345-4e2e1500-9d0d-11ea-8c82-0578136a9c69.png)

**Comment by Zolko-123** [comment]
yes, this is expected, and depends on the complexity of your model and the power of your computer.

**Comment by jkadofo** [comment]
I realize you can also control the fluidity by adjusting the "Step Size" and "Sleep" parameters. I expect a longer sleep time to be easy on slower computers, then you can make the animation look faster by increasing the step size.
