### ISSUE TITLE
missing sketch info

### ISSUE THREAD

**Issue by donovaly** [Zolko-123/FreeCAD_Examples#4]
I'm stepping through the Tutorial 1 and I am stuck at the sketch. The issue is that the image:
https://raw.githubusercontent.com/Zolko-123/FreeCAD_Examples/master/Asm4_Tutorial1/Sketch_Axis.png
does not provide all info to get a fully constraint sketch. Can you please update the image?

**Comment by Zolko-123** [comment]
What's the problem with a sketch that is not fully constrained ?

**Comment by donovaly** [comment]
> What's the problem with a sketch that is not fully constrained ?

It is just that when you learn CAD they'll tell you to fully constrain sketches before extruding them to the third dimension. Also most of the FC learning videos I have seen so far on YouTube follow this guideline, also the video of the Tutorial 1. In this video they have this info while if you just do the tutorial in text form you have not. So if you could just upload a new screenshot image with all the dimensions to get a fully constrained sketch would be nice. If you think, this is not necessary, could you please add a sentence about this to the tutorial?

**Comment by Zolko-123** [comment]
can you do write in a comment about not fully constraint sketch please, and I'll add your PR ?
