### ISSUE TITLE
wrong cursor symbol

### ISSUE THREAD

**Issue by donovaly** [Zolko-123/FreeCAD_Examples#5]
In Tutorial 1 you wrote: `Note how the cursor changes to a small hand `

However here with Assembly4 0.9.3 and
```
OS: Windows 10 (10.0)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.21614 (Git)
Build type: Release
Branch: master
Hash: fc6a449fbae1fda767d52f414cb8c53424dff607
Python version: 3.6.8
Qt version: 5.12.1
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: German/Germany (de_DE)
```

I got this symbol:
![Cursor-looks-different](https://user-images.githubusercontent.com/1828501/84583230-b21c9880-adf6-11ea-8448-a5102423c476.jpg)

The operation succeeds, it is just that the cursor symbol is different. Maybe this Windows-specific? However, maybe this should be mentioned that people can continue with the tutorial and don't wonder as I did.

**Comment by Zolko-123** [comment]
Thank-you, I'll add the note
