### ISSUE TITLE
Tuturial 3 not linked in Readme.md

### ISSUE THREAD

**Issue by donovaly** [Zolko-123/FreeCAD_Examples#6]
The third tutorial is not linked in Readme.md:

![firefox_pE64HjFw5f](https://user-images.githubusercontent.com/1828501/84592178-00a45400-ae44-11ea-8ad1-ec0ac0ed5db4.png)

**Comment by donovaly** [comment]
Here is the PR: https://github.com/Zolko-123/FreeCAD_Examples/pull/8

**Comment by Zolko-123** [comment]
this tutorial is not yet written
